import { Zap, Sparkles, Flame, Star, Users } from 'lucide-react';

export const PLANS = [
  {
    id: 'free',
    name: 'Free',
    subtitle: 'The Beginning',
    price: 0,
    description: 'Start your journey',
    features: ['7 builder calls/month', '3 projects', 'Community support', 'Core WebOS access'],
    limits: { calls: 7, projects: 3 },
    color: 'gray',
    icon: Zap,
  },
  {
    id: 'spark',
    name: 'Spark',
    subtitle: 'Wonder Into',
    price: 9.99,
    description: 'Ignite your curiosity',
    features: ['30 builder calls/month', '10 projects', 'Priority support'],
    limits: { calls: 30, projects: 10 },
    color: 'cyan',
    icon: Sparkles,
  },
  {
    id: 'emergent',
    name: 'Emergent',
    subtitle: 'Discovering',
    price: 17.99,
    description: 'Find your flow',
    features: ['100 builder calls/month', 'Unlimited projects', 'Advanced search'],
    limits: { calls: 100, projects: '∞' },
    color: 'purple',
    icon: Star,
  },
  {
    id: 'catalyst',
    name: 'Catalyst',
    subtitle: 'Supreme Value',
    price: 29.99,
    description: 'Accelerate everything',
    features: ['Unlimited Local & BYOK access', 'Unlimited projects', 'Full Agent Swarm', 'Priority queue'],
    limits: { calls: '∞', projects: '∞' },
    color: 'amber',
    icon: Flame,
    popular: true,
  },
  {
    id: 'nova',
    name: 'Nova',
    subtitle: 'Ultimate',
    price: 75.00,
    description: 'Unlimited power',
    features: ['Unlimited with BYOK', 'Unlimited projects', 'Advanced analytics', 'Secrets manager'],
    limits: { calls: '∞', projects: '∞' },
    color: 'pink',
    icon: Star,
  },
  {
    id: 'catalytic-crew',
    name: 'Catalytic Crew',
    subtitle: 'Enterprise',
    price: 349.99,
    description: 'For teams and organizations',
    features: ['Everything in Nova', 'Unlimited team seats', 'SSO & SAML', 'Dedicated support', 'Custom contracts', 'On-premise option'],
    limits: { calls: '∞', projects: '∞' },
    color: 'indigo',
    icon: Users,
  },
];
