
export const TIER_CONFIG = {
  free: {
    id: 'free',
    name: 'Free',
    price: 0,
    creditsPerDay: 7,
    creditsPerMonth: 20,
    canBringOwnKeys: false,
    localAIUnlimited: false,
    webOS: false,
    priorityInference: false,
    liveSupport: false,
    catalystBadge: false,
    exhaustiveResearchPerMonth: 0,
    color: 'text-white/80',
    accentColor: '#e5e7eb',
  },
  spark: {
    id: 'spark',
    name: 'Spark',
    price: 9.99,
    creditsPerDay: 30,
    creditsPerMonth: 100,
    canBringOwnKeys: false,
    localAIUnlimited: true,
    webOS: 'limited',
    priorityInference: false,
    liveSupport: false,
    catalystBadge: false,
    exhaustiveResearchPerMonth: 0,
    color: 'text-cyan-400',
    accentColor: '#22d3ee',
  },
  emergent: {
    id: 'emergent',
    name: 'Emergent',
    price: 17.99,
    creditsPerDay: 100,
    creditsPerMonth: 250,
    canBringOwnKeys: false,
    localAIUnlimited: true,
    webOS: true,
    priorityInference: false,
    liveSupport: false,
    catalystBadge: false,
    exhaustiveResearchPerMonth: 0,
    color: 'text-fuchsia-400',
    accentColor: '#e879f9',
  },
  catalyst: {
    id: 'catalyst',
    name: 'Catalyst',
    price: 29.99,
    creditsPerDay: 250,
    creditsPerMonth: 500,
    canBringOwnKeys: true,
    localAIUnlimited: true,
    webOS: true,
    priorityInference: true,
    liveSupport: true,
    catalystBadge: true,
    exhaustiveResearchPerMonth: 1,
    color: 'text-amber-400',
    accentColor: '#fbbf24',
  },
  nova: {
    id: 'nova',
    name: 'Nova',
    price: 75.00,
    creditsPerDay: 500,
    creditsPerMonth: 750,
    canBringOwnKeys: true,
    localAIUnlimited: true,
    webOS: true,
    priorityInference: true,
    liveSupport: true,
    catalystBadge: true,
    exhaustiveResearchPerMonth: 2,
    color: 'text-rose-400',
    accentColor: '#f43f5e',
  },
  'catalytic-crew': {
    id: 'catalytic-crew',
    name: 'Catalytic Crew',
    price: 349.99,
    creditsPerDay: 1000,
    creditsPerMonth: 5000,
    canBringOwnKeys: true,
    localAIUnlimited: true,
    webOS: true,
    priorityInference: true,
    liveSupport: true,
    catalystBadge: true,
    exhaustiveResearchPerMonth: 5,
    color: 'text-indigo-400',
    accentColor: '#818cf8',
  },
};
